// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Education struct {
	ID           string `json:"id"`
	UserID       string `json:"user_id"`
	School       string `json:"school"`
	Degree       string `json:"degree"`
	FieldOfStudy string `json:"field_of_study"`
	StartDate    string `json:"start_date"`
	EndDate      string `json:"end_date"`
}

type Experience struct {
	ID             string `json:"id"`
	UserID         string `json:"user_id"`
	Title          string `json:"title"`
	EmploymentType string `json:"employment_type"`
	CompanyName    string `json:"company_name"`
	Location       string `json:"location"`
	StartDate      string `json:"start_date"`
	EndDate        string `json:"end_date"`
}

type User struct {
	ID              string `json:"id"`
	FirstName       string `json:"first_name"`
	LastName        string `json:"last_name"`
	Job             string `json:"job"`
	Email           string `json:"email"`
	Password        string `json:"password"`
	ProfilePhoto    string `json:"profile_photo"`
	BackgroundPhoto string `json:"background_photo"`
	Headline        string `json:"headline"`
	IsActive        bool   `json:"is_active"`
	ActiveCode      string `json:"active_code"`
}

type Comment struct {
	ID      string `json:"id"`
	PostID  string `json:"post_id"`
	UserID  string `json:"user_id"`
	ReplyID string `json:"reply_id"`
	Content string `json:"content"`
	Likes   int    `json:"likes"`
}

type ConnectInvitation struct {
	ID        *int   `json:"id"`
	UserSrcID string `json:"user_src_id"`
	UserDstID string `json:"user_dst_id"`
	Message   string `json:"message"`
}

type Connection struct {
	UserID      string `json:"user_id"`
	ConnectedID string `json:"connected_id"`
}

type FollowedUser struct {
	UserID     string `json:"user_id"`
	FollowedID string `json:"followed_id"`
}

type InputEdu struct {
	UserID       string `json:"user_id"`
	School       string `json:"school"`
	Degree       string `json:"degree"`
	FieldOfStudy string `json:"field_of_study"`
	StartDate    string `json:"start_date"`
	EndDate      string `json:"end_date"`
}

type InputExp struct {
	UserID         string `json:"user_id"`
	Title          string `json:"title"`
	EmploymentType string `json:"employment_type"`
	CompanyName    string `json:"company_name"`
	Location       string `json:"location"`
	StartDate      string `json:"start_date"`
	EndDate        string `json:"end_date"`
}

type JobPost struct {
	ID          string `json:"id"`
	LogoURL     string `json:"logo_url"`
	CompanyName string `json:"company_name"`
	JobName     string `json:"job_name"`
	Location    string `json:"location"`
}

type LikedComment struct {
	CommentID string `json:"comment_id"`
	UserID    string `json:"user_id"`
}

type LikedPost struct {
	PostID string `json:"post_id"`
	UserID string `json:"user_id"`
}

type NewJobPost struct {
	LogoURL     string `json:"logo_url"`
	CompanyName string `json:"company_name"`
	JobName     string `json:"job_name"`
	Location    string `json:"location"`
}

type NewUser struct {
	FirstName string `json:"first_name"`
	LastName  string `json:"last_name"`
	Email     string `json:"email"`
	Password  string `json:"password"`
}

type Post struct {
	ID          string `json:"id"`
	UserID      string `json:"user_id"`
	ContentText string `json:"content_text"`
	URL         string `json:"url"`
	Type        string `json:"type"`
	Likes       int    `json:"likes"`
	Comments    int    `json:"comments"`
}

type UpdateUser struct {
	FirstName       string `json:"first_name"`
	LastName        string `json:"last_name"`
	Email           string `json:"email"`
	Password        string `json:"password"`
	ProfilePhoto    string `json:"profile_photo"`
	BackgroundPhoto string `json:"background_photo"`
	Headline        string `json:"headline"`
	Job             string `json:"job"`
}
